name: Continuous integration

on:
  pull_request: null
  push:
    branches:
      - main
      - develop
      - 2.x

jobs:
  static-analysis:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version: ['8.0']
        command: ['cs', 'stan', 'swagger:validate']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: openswoole-4.9.1
          coverage: none
      - run: composer install --no-interaction --prefer-dist
      - run: composer ${{ matrix.command }}

  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version: ['8.0', '8.1']
        test-group: ['unit', 'api']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start database server
        if: ${{ matrix.test-group == 'api' }}
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d shlink_db_postgres
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: openswoole-4.9.1
          coverage: pcov
          ini-values: pcov.directory=module
      - run: composer install --no-interaction --prefer-dist
      - run: composer test:${{ matrix.test-group }}:ci
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.php-version == '8.0' }}
        with:
          name: coverage-${{ matrix.test-group }}
          path: |
            build/coverage-${{ matrix.test-group }}
            build/coverage-${{ matrix.test-group }}.cov

  db-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version: ['8.0', '8.1']
        platform: ['sqlite:ci', 'mysql', 'maria', 'postgres', 'ms']
    env:
      LC_ALL: C
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install MSSQL ODBC
        if: ${{ matrix.platform == 'ms' }}
        run: sudo ./data/infra/ci/install-ms-odbc.sh
      - name: Start database server
        if: ${{ matrix.platform != 'sqlite:ci' }}
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d shlink_db_${{ matrix.platform }}
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: openswoole-4.9.1, pdo_sqlsrv-5.10.0
          coverage: pcov
          ini-values: pcov.directory=module
      - run: composer install --no-interaction --prefer-dist
      - name: Create test database
        if: ${{ matrix.platform == 'ms' }}
        run: docker-compose exec -T shlink_db_ms /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Passw0rd!' -Q "CREATE DATABASE shlink_test;"
      - name: Run tests
        run: composer test:db:${{ matrix.platform }}
      - name: Upload code coverage
        uses: actions/upload-artifact@v2
        if: ${{ matrix.php-version == '8.0' && matrix.platform == 'sqlite:ci' }}
        with:
          name: coverage-db
          path: |
            build/coverage-db
            build/coverage-db.cov

  mutation-tests:
    needs:
      - tests
      - db-tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version: ['8.0', '8.1']
        test-group: ['unit', 'db', 'api']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: openswoole-4.9.1
          coverage: pcov
          ini-values: pcov.directory=module
      - run: composer install --no-interaction --prefer-dist
      - uses: actions/download-artifact@v2
        with:
          path: build
      - if: ${{ matrix.test-group == 'unit' }}
        run: composer infect:ci:unit
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
      - if: ${{ matrix.test-group != 'unit' }}
        run: composer infect:ci:${{ matrix.test-group }}

  upload-coverage:
    needs:
      - tests
      - db-tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version: ['8.0']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          ini-values: pcov.directory=module
      - uses: actions/download-artifact@v2
        with:
          path: build
      - run: mv build/coverage-unit/coverage-unit.cov build/coverage-unit.cov
      - run: mv build/coverage-db/coverage-db.cov build/coverage-db.cov
      - run: mv build/coverage-api/coverage-api.cov build/coverage-api.cov
      - run: wget https://phar.phpunit.de/phpcov-8.2.0.phar
      - run: php phpcov-8.2.0.phar merge build --clover build/clover.xml
      - name: Publish coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./build/clover.xml

  delete-artifacts:
    needs:
      - mutation-tests
      - upload-coverage
    runs-on: ubuntu-20.04
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            coverage-unit
            coverage-db
            coverage-api

  build-docker-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@v1
        id: changed-dockerfile
        with:
          paths: ./Dockerfile
      - if: ${{ steps.changed-dockerfile.outputs.changed == 'true' }}
        run: docker build -t shlink-docker-image:temp .
      - if: ${{ steps.changed-dockerfile.outputs.changed != 'true' }}
        run: echo "Dockerfile didn't change. Skipped"
